name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node.js environment
      uses: actions/setup-node@v3
    - name: Install dependencies and build
      working-directory: .
      run: |
        npm install
        npm run build
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Deploy with rsync
      run:  sshpass -p "${{ secrets.PASSPHRASE}}" rsync -avz ./dist/ juggler39@juggler39.myjino.ru:/domains/prochess.ru/